### ISSUE TITLE
Scrolling tab bar?

### ISSUE THREAD

**Issue by Hebgbs** [l0c4lh057/BetterDiscordStuff#112]
**Is your feature request related to a problem? Please describe.**
I would like it so the tabs are in a single row, so the tabs do not occupy more space in Discord tha it needs to.

**Describe the solution you'd like**
Use of a flexbox fo the tabs, and some JQuery code to make them scrollable.

**Additional context**
Here's the code I've managed to conjure so this functionality works:
```css
#channelTabs-container > .channelTabs-tabContainer {
    display: flex !important;
    overflow-x: scroll;
    overflow: hidden;
}
```
The last bit which is required by the plugin is some JQuery code to translate scrolling into horizontal scroll, so shift isn't required to scroll. This is behaviour similar to Firefox and Chrome browsers, figured for people on a tight vertical screen budget it would be most beneficial for them.

Other additions could be typing indicators shown as an overlay when tabs that have people typing in them are out of viewport (as determined by the typing indicator itself, not the tab) and maybe a new message indicator similar to Discord's guild bar behaviour.

**Comment by l0c4lh057** [comment]
I like this idea. Instead of using jQuery (which BD luckily does not ship anymore) a scrollwheel listener could be added to the element (<https://alvarotrigo.com/blog/scroll-horizontally-with-mouse-wheel-vanilla-java/>, probably needs the ref since the plugin uses react). If someone provides a PR for this I'd happily accept it, otherwise this is low priority right now and might now be implemented soon.

**Comment by Hebgbs** [comment]
Further appending onto my CSS< I managed to get the scrolling working. I am not sure how to integrate the JavaScript into your code;
```css
#channelTabs-container > .channelTabs-tabContainer {
    display: flex !important;
    overflow-x: scroll;
}

#channelTabs-container > .channelTabs-tabContainer::-webkit-scrollbar {
    display: none !important;
}

.channelTabs-tab {
    min-width: 220px;
}
```
but I am sure given enough time and effort I can figure out where to drop it in.
