### ISSUE TITLE
Bookmark does not fill the full page

### ISSUE THREAD

**Issue by RealYusufIsmail** [l0c4lh057/BetterDiscordStuff#140]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**

**To Reproduce**
1. Use the latest version of ChannelTabs

**Expected behavior**
To fill the page

**Screenshots**
<img width="2240" alt="Screenshot 2022-08-03 at 20 31 07" src="https://user-images.githubusercontent.com/67903886/182693459-ea531283-a9e8-43ba-8e56-299b7bb4660e.png">

<img width="2240" alt="Screenshot 2022-08-03 at 20 31 26" src="https://user-images.githubusercontent.com/67903886/182693517-40a23516-60f5-4fac-b5b8-d1d8571bd5f3.png">

**Information (please complete the following information):**
 - OS: [MacOS]
 - Plugin Version: [2.6.1]
 - Discord version: [Stable]
 - Compact Mode enabled? [no]

**Additional context**

**Comment by maenDisease** [comment]
I don't see the issue?

**Comment by RealYusufIsmail** [comment]
thats weird

**Comment by RealYusufIsmail** [comment]
<img width="2240" alt="Screenshot 2022-08-03 at 20 38 30" src="https://user-images.githubusercontent.com/67903886/182694654-27fafb29-70bb-4d3b-810e-f8b97a2748e3.png">
it is this extra space

**Comment by maenDisease** [comment]
are you full screen

**Comment by RealYusufIsmail** [comment]
yes

**Comment by maenDisease** [comment]
see here https://github.com/l0c4lh057/BetterDiscordStuff/issues/133#issuecomment-1120269170

**Comment by RealYusufIsmail** [comment]
I will see if it works

**Comment by RealYusufIsmail** [comment]
were am i supposed to put
 ```css
html.platform-osx .typeMacOS-3V4xXE {
	position: absolute;
	width: unset;
}

.channelTabs-tabContainer::before {
	content:'';
	height: 100%;
	width: 72px;
}

.channelTabs-tabContainer {
	-webkit-app-region: drag;
}

.channelTabs-tabContainer>* {
	-webkit-app-region: no-drag;
}

html .channelTabs-newTab {
	margin-right: calc(6px + 72px);
}
```
