### ISSUE TITLE
[Channel Tabs] Request: An option to move Discord's titlebar buttons to channelTabs element

### ISSUE THREAD

**Issue by KKchoco** [l0c4lh057/BetterDiscordStuff#75]
I guess it would be nice to have titlebar buttons just like in any browser
I've tried to take "Old Title Bar" plugin as start to modify it into ChannelTabs plugin, but I'm not good enough unfortunately.
Right now I'm also using "Old Title Bar" plugin but it not very comfortable to have titlebar buttons under channel tabs line.

**Comment by TheChilliPL** [comment]
I tried doing something like that myself, with custom CSS. I have the compact mode on, may not work without it:
![image](https://user-images.githubusercontent.com/18823939/189504767-9026c127-45c8-49cb-b42b-98cfc5d1cd46.png)
Dragging works, everything that should be clickable is clickable. I moved the Discord logo to the right next to the buttons instead of removing it.

<details><summary>If you want to see the code, click here</summary>

```css
/* Merge title bar with channel tabs */
.titleBar-1it3bQ {
    position: absolute;
    pointer-events: none;
    right: 0;
    top: 0;
    width: 160px;
    height: 30px !important;
    align-items: center;
    vertical-align: middle;
}

.winButton-3UMjdg {
    position: static;
    height: 100%;
}

.wordmark-2u86JB {
    position: static;
    order: 999;
}

#channelTabs-container {
    /* height: 30px; */
    padding-right: 190px !important;
}

.channelTabs-tabContainer {
    height: 30px;
    -webkit-app-region: drag !important;
}

.channelTabs-tabContainer * {
    -webkit-app-region: no-drag !important;
}

#channelTabs-settingsMenu {
    -webkit-app-region: no-drag !important;
    right: 160px !important;
    width: 30px !important;
    height: 30px !important;
}
```

It may not be the most beautiful, uses `!important`s quite a bit, but works!

</details>
